# Generated by Django 5.1.1 on 2024-10-07 16:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("advertisements", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advertisement",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
